import Lukasiewicz.Correspondence

/-!
# The Second Isomorphism Theorem

This module completes the classical suite of isomorphism theorems for
MV-algebras. Building on the quotient construction (`Quotient.lean`) and the
First Isomorphism Theorem, it proves:

> **Second Isomorphism Theorem.** For a sub-MV-algebra `S ≤ A` and an ideal
> `I ⊴ A`, there is an isomorphism `S / (S ∩ I) ≅ (S + I)/I`.

The proof is the classical one-liner *as a corollary of the First Isomorphism
Theorem*: consider the composite homomorphism

$$\varphi : S \hookrightarrow A \xrightarrow{\ \pi\ } A/I, \qquad s \mapsto \llbracket s \rrbracket .$$

Its **kernel** is `{s ∈ S : s ∈ I} = S ∩ I`, and its **image** is
`{⟦s⟧ : s ∈ S}`, which is exactly `(S + I)/I` — the sub-MV-algebra of `A/I`
generated by the classes of `S`. The First Isomorphism Theorem applied to `φ`
therefore yields `S / (S ∩ I) ≅ (S + I)/I`.

As with the rest of the quotient theory, everything here is **choice-free**:
the only axioms are `Quot.sound` and `propext`.
-/

namespace Luk
namespace MVAlgebra

variable {A : Type _} [MVAlgebra A]

/-! ## The composite `S ↪ A → A/I` -/

/-- The **composite homomorphism** `S ↪ A → A/I`, sending `s ↦ ⟦s⟧`. Because the
    sub-MV-algebra operations and the quotient operations are both the ambient
    ones, every preservation law holds by `rfl`. -/
def subQuotientHom (S : SubMVAlgebra A) (I : Ideal A) :
    MVHom S.Subtype (QuotientByIdeal I) where
  toFun := fun s => Quotient.mk I.setoid s.val
  map_zero := rfl
  map_oplus := fun _ _ => rfl
  map_neg := fun _ => rfl

/-! ## The ideal `S ∩ I` -/

/-- The ideal **`S ∩ I`**, regarded as an ideal of the sub-MV-algebra `S`: those
    elements of `S` whose underlying value lies in `I`. Downward closure uses the
    fact that the order on the subtype is the ambient order on values. -/
def subInterIdeal (S : SubMVAlgebra A) (I : Ideal A) : Ideal S.Subtype where
  carrier := fun s => I.carrier s.val
  zero_mem := I.zero_mem
  downward_closed := by
    intro s t hs hts
    -- `t ≤ s` in the subtype unfolds to `t.val ≤ s.val` in `A`.
    have hv : le t.val s.val :=
      congrArg Subtype.val (hts : oplus (neg t) s = (one : S.Subtype))
    exact I.downward_closed hs hv
  oplus_mem := by
    intro s t hs ht
    exact I.oplus_mem hs ht

/-- **The kernel of `S ↪ A → A/I` is `S ∩ I`.** A subalgebra element `s` lies in
    the kernel iff `⟦s⟧ = 0`, iff `s ∈ I`. -/
theorem ker_subQuotientHom (S : SubMVAlgebra A) (I : Ideal A) (s : S.Subtype) :
    (subQuotientHom S I).ker.carrier s ↔ (subInterIdeal S I).carrier s := by
  show (Quotient.mk I.setoid s.val = Quotient.mk I.setoid zero) ↔ I.carrier s.val
  constructor
  · intro h
    have hh : I.carrier (dist s.val zero) := Quotient.exact h
    rw [dist_zero_right] at hh
    exact hh
  · intro h
    apply Quotient.sound
    show I.carrier (dist s.val zero); rw [dist_zero_right]; exact h

/-! ## The image `(S + I)/I` -/

/-- **The image of `S ↪ A → A/I` is `(S + I)/I`** — the set of classes `⟦a⟧`
    such that `a` is congruent (mod `I`) to some element of `S`. Concretely,
    a class lies in the image iff it has a representative *in* `S`. -/
theorem mem_image_subQuotientHom (S : SubMVAlgebra A) (I : Ideal A)
    (p : QuotientByIdeal I) :
    (MVHom.image (subQuotientHom S I)).carrier p ↔ ∃ a, S.carrier a ∧ Quotient.mk I.setoid a = p := by
  constructor
  · rintro ⟨⟨a, ha⟩, hp⟩
    exact ⟨a, ha, hp⟩
  · rintro ⟨a, ha, hp⟩
    exact ⟨⟨a, ha⟩, hp⟩

/-! ## The Second Isomorphism Theorem -/

/-- **The Second Isomorphism Theorem.** For a sub-MV-algebra `S` and an ideal
    `I` of `A`:

    * the canonical map `S / (S ∩ I) → (S + I)/I` is a bijective MV-homomorphism
      (an isomorphism), and
    * the kernel of the defining composite `S ↪ A → A/I` is exactly `S ∩ I`.

    Together: `S / (S ∩ I) ≅ (S + I)/I`. This is obtained by applying the First
    Isomorphism Theorem to the composite `subQuotientHom S I`. -/
theorem secondIsomorphismTheorem (S : SubMVAlgebra A) (I : Ideal A) :
    (∃ ψ : MVHom (QuotientByIdeal (subQuotientHom S I).ker)
                 (MVHom.image (subQuotientHom S I)).Subtype,
        MVHom.Injective ψ ∧ MVHom.Surjective ψ)
    ∧ (∀ s, (subQuotientHom S I).ker.carrier s ↔ (subInterIdeal S I).carrier s) :=
  ⟨firstIsomorphismTheorem (subQuotientHom S I), ker_subQuotientHom S I⟩

end MVAlgebra
end Luk
